### ISSUE TITLE
选择网卡出错

### ISSUE THREAD

**Issue by kerdiox** [Soleil0707/sniffer#1]
你好，在我选择网卡抓包时出现了错误：
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\Sniffer-main\gui.py", line 264, in switch_capture_panel
    index = int(iface[0])
ValueError: invalid literal for int() with base 10: 'libpcap'

**Comment by kerdiox** [comment]
找出问题所在了，应为iface[1]
